#!/bin/bash
#Set custom PATHS, aliases, etc.

echo "`whoami`@`hostname`: Thank you for opening a new terminal!"

# ---------------------------------------------------------------------------- #
# Add to PATH - How you add more commands to the command line
# ---------------------------------------------------------------------------- #
# setenv PATH "/usr/local/bin:${PATH}"

# ---------------------------------------------------------------------------- #
# Environment Variables
# ---------------------------------------------------------------------------- #
# Set 'ls' colors and options
export CLICOLOR=1
export LSCOLORS=Gxfxcxdxbxegedabagacad

#Set extended wildcards
# % ls !(not_this_file.txt)
shopt -s extglob

# Default Editor
export EDITOR='emacs -nw'

# After each command check if the window size needs to change
shopt -s checkwinsize

# set a default location
export DEFAULT_LOCATION=${HOME}

# ---------------------------------------------------------------------------- #
# Move To Default location
# ---------------------------------------------------------------------------- #
if [ "$PWD" == "${HOME}" ]
then cd $DEFAULT_LOCATION
fi

# ---------------------------------------------------------------------------- #
# Modify Terminal Window
# ---------------------------------------------------------------------------- #
# source ~/.prompt_bash # Could put the this section into it's own script

# Set terminal title
# PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
PROMPT_COMMAND='echo -ne "\033]0; ${HOSTNAME}:${PWD}\007"'

# Set command prompt
# For full list, "man bash" and search to 2nd "PROMPTING" or see:
# http://tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html
# also: http://www.yolinux.com/HOWTO/Bash-Prompt-HOWTO.html
# \u : username
# \h : host to first "."
# \w : current full working directory
# \W : last part of path
BLACK="\[\033[0;30m\]"
BLUE="\[\033[0;34m\]"
GREEN="\[\033[0;32m\]"
CYAN="\[\033[0;36m\]"
RED="\[\033[0;31m\]"
PURPLE="\[\033[0;35m\]"
BROWN="\[\033[0;33m\]"
LIGHT_GRAY="\[\033[0;37m\]"
DARK_GRAY="\[\033[1;30m\]"
BOLD_BLUE="\[\033[1;34m\]"
BOLD_GREEN="\[\033[1;32m\]"
BOLD_CYAN="\[\033[1;36m\]"
BOLD_RED="\[\033[1;31m\]"
BOLD_PURPLE="\[\033[1;35m\]"
YELLOW="\[\033[1;33m\]"
WHITE="\[\033[1;37m\]"
RESET="\[\033[m\]"

# set the primary prompt
export PS1="$BOLD_GREEN[\W]$GREEN$ $RESET"

# For multi-line commands:
export PS2="$BOLD_GREEN> $RESET"


# ############################################################################ #
# Aliases to commands ===>

# ---------------------------------------------------------------------------- #
# Modify Builtin Commands
# ---------------------------------------------------------------------------- #
alias cp='cp -i' # interactive so you don't accidentally overwrite existing files
alias mv='mv -i'
alias rm='rm -i' # use rm -f if you want to force removal
alias srm='srm -i'
alias du='du -csh'

# ---------------------------------------------------------------------------- #
# Connivence Aliases
# ---------------------------------------------------------------------------- #
alias remove='rm -rf'
alias lsl='ls -haltr' #-halter  the "-e" is part of the "-l"
alias lss='ls -hsl'
alias resource='source ~/.bashrc'


# for finder
# alias finder='open .' # open current directory in finder on MacOSX
# show/hide hidded files in finder

# for information about chmod
alias chmodinfo='echo "chmod information:\n 7 = full (111) \n 6 = read/write (110)\n 5 = read/exec (101)\n 4 = read (100)\n 3 = write/exec (011)\n 2 = write (010)\n 1 = exec (001)\n 0 = none (000)\n \n SHELL$ chmod 754 foo.txt\n  = gives user (u) full, group (g) read/exec,  and  others (o) read only"'

# Location Shortcuts
#alias cda="cd ${ASTROHOME}"

# ---------------------------------------------------------------------------- #
# Application Aliases
# ---------------------------------------------------------------------------- #

# Terminals
alias xterm='xterm -fa Monaco -fs 9.5 -fg white -bg black'

# Python aliases
alias py='python'
alias ipy='ipython'

# Text Editors
alias em="emacs"

# ---------------------------------------------------------------------------- #
# Aliases for network connections
# ---------------------------------------------------------------------------- #
alias astro03='ssh -Y u0565532@astro03.astro.utah.edu'
# also check out ~/.ssh/config

# reconnecting to the UConnect WiFi
# alias reconnect_uconnect="networksetup -setairportnetwork en1 UConnect" # on MacOSX

# for syncing astronomy directories
# alias astrosync "/Applications/astro/rsync_script.py"

# ---------------------------------------------------------------------------- #
# Research Specific Aliases
# ---------------------------------------------------------------------------- #

# ---------------------------------------------------------------------------- #
# Misc Aliases
# ---------------------------------------------------------------------------- #
alias y='echo YES!'
alias n='echo NO!'
alias textwars='telnet towel.blinkenlights.nl'
alias matrix='LC_ALL=C tr -c "[:digit:]" " " < /dev/urandom | dd cbs=$COLUMNS conv=unblock | GREP_COLOR="1;32" grep --color "[^ ]"'




